/*
 * What the LVGL heap would hold on the ESP32.
 *
 * The PC build runs with 8-byte pointers, so its heap figures overstate the
 * device's. Instead of guessing a ratio, walk every live LVGL object and add
 * up the heap blocks it owns - instance, style arrays, local styles and their
 * property arrays, child and event arrays, label text, meter and chart lists,
 * running animations and timers - twice: once with this PC's struct sizes and
 * once with the 32-bit ones (lv_sizes.c compiled with -m32), each rounded the
 * way LVGL's TLSF allocator rounds on that target.
 *
 * The PC model is checked against the PC's own lv_mem_monitor(); what the
 * model cannot see (the theme's styles, the display, LVGL's own lists) is
 * measured on the PC as a baseline and scaled by the same 32/64 ratio.
 */
#include <lvgl.h>

#include "host.h"
#include "lv_sizes.h"      // generated by run.py

extern "C" {
extern lv_ll_t _lv_anim_ll;
extern lv_ll_t _lv_timer_ll;
}

namespace {

size_t block(const LvSizes &z, size_t n) {
    if (!n) return 0;
    const size_t align = z.ptr;                 // TLSF ALIGN_SIZE per target
    const size_t minb  = 3 * z.ptr;             // block_size_min
    size_t a = (n + align - 1) / align * align;
    if (a < minb) a = minb;
    return a + z.size_t_;                       // block_header_overhead
}

size_t llNode(const LvSizes &z, size_t payload) { return block(z, payload + 2 * z.ptr); }

size_t instance(const LvSizes &z, const lv_obj_t *o) {
    const lv_obj_class_t *c = o->class_p;
    if (c == &lv_label_class) return z.label;
    if (c == &lv_arc_class || c == &lv_spinner_class) return z.arc;
    if (c == &lv_bar_class)   return z.bar;
    if (c == &lv_img_class)   return z.img;
    if (c == &lv_meter_class) return z.meter;
    if (c == &lv_chart_class) return z.chart;
    return z.obj;
}

size_t walk(const LvSizes &z, lv_obj_t *o, size_t &objects) {
    objects++;
    size_t b = block(z, instance(z, o));
    if (o->style_cnt) b += block(z, o->style_cnt * z.obj_style);
    for (uint32_t i = 0; i < o->style_cnt; i++) {
        if (!o->styles[i].is_local) continue;
        const lv_style_t *s = o->styles[i].style;
        b += block(z, z.style);
        if (s->prop_cnt > 1) b += block(z, s->prop_cnt * (z.style_value + z.style_prop));
    }
    if (o->spec_attr) {
        b += block(z, z.spec_attr);
        b += block(z, o->spec_attr->child_cnt * z.ptr);
        b += block(z, o->spec_attr->event_dsc_cnt * z.event_dsc);
    }
    if (o->class_p == &lv_label_class) {
        const lv_label_t *l = (const lv_label_t *)o;
        if (l->text && !l->static_txt) b += block(z, strlen(l->text) + 1);
    }
    if (o->class_p == &lv_meter_class) {
        lv_meter_t *m = (lv_meter_t *)o;
        void *n;
        _LV_LL_READ(&m->scale_ll, n) b += llNode(z, z.meter_scale);
        _LV_LL_READ(&m->indicator_ll, n) b += llNode(z, z.meter_indicator);
    }
    if (o->class_p == &lv_chart_class) {
        lv_chart_t *c = (lv_chart_t *)o;
        void *sp;
        _LV_LL_READ(&c->series_ll, sp) {
            const lv_chart_series_t *s = (const lv_chart_series_t *)sp;
            b += llNode(z, z.chart_series);
            if (!s->y_ext_buf_assigned) b += block(z, c->point_cnt * z.coord);
        }
    }
    for (uint32_t i = 0; i < lv_obj_get_child_cnt(o); i++)
        b += walk(z, lv_obj_get_child(o, i), objects);
    return b;
}

size_t model(const LvSizes &z, size_t &objects) {
    objects = 0;
    size_t b = 0;
    lv_disp_t *d = lv_disp_get_default();
    for (uint32_t i = 0; i < d->screen_cnt; i++) b += walk(z, d->screens[i], objects);
    b += walk(z, d->top_layer, objects);
    b += walk(z, d->sys_layer, objects);
    void *n;
    _LV_LL_READ(&_lv_anim_ll, n)  b += llNode(z, z.anim);
    _LV_LL_READ(&_lv_timer_ll, n) b += llNode(z, z.timer);
    return b;
}

size_t s_baseline64 = 0;

}  // namespace

void host::heapBaseline() {
    lv_mem_monitor_t m;
    lv_mem_monitor(&m);
    s_baseline64 = m.total_size - m.free_size;
}

size_t host::deviceBytes(lv_obj_t *o) {
    size_t n;
    return walk(LV_SIZES_TARGET, o, n);
}

host::HeapReport host::heapReport() {
    HeapReport r{};
    lv_mem_monitor_t m;
    lv_mem_monitor(&m);
    r.pcUsed = m.total_size - m.free_size;
    r.pcPeak = m.max_used;
    size_t objs;
    r.pcModel     = model(LV_SIZES_HOST, objs);
    r.objects     = objs;
    r.targetModel = model(LV_SIZES_TARGET, objs);
    // What the walk cannot see: the theme, the display, LVGL's own lists.
    const double ratio  = r.pcModel ? (double)r.targetModel / r.pcModel : 0.6;
    const double unseen = (double)r.pcUsed - (double)r.pcModel;
    r.targetUsed = (size_t)(r.targetModel + (unseen > 0 ? unseen : 0) * ratio);
    // Transient render buffers are sized in pixels, the same on both.
    r.targetPeak = r.targetUsed + (r.pcPeak > r.pcUsed ? r.pcPeak - r.pcUsed : 0);
    r.budget     = LV_MEM_SIZE_TARGET;
    r.baseline64 = s_baseline64;
    return r;
}
