"""
Compile the Gauge Studio page into the firmware.

Runs before every build (platformio.ini: extra_scripts = pre:tools/embed_studio.py)
and can also be run by hand:

    python tools/embed_studio.py

Reads   data/www/index.html
Writes  src/config/StudioPage.h   the page, gzipped, as a byte array

Why: the studio used to be served from LittleFS, so changing it meant
`pio run -t uploadfs` - which rewrites the whole filesystem and with it the
layout and touch calibration stored on the device. Built into the firmware,
the page is always the one that matches the firmware, and flashing updates it.

The gzip header carries no timestamp, and the header file is only rewritten
when its content changes, so an unchanged page never triggers a recompile.

This file is identical in both display projects.
"""
import gzip
import io
import os
import sys


def project_dir():
    try:
        Import("env")                                  # noqa: F821 (SCons)
        return env.subst("$PROJECT_DIR")               # noqa: F821
    except NameError:
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def build(root):
    src = os.path.join(root, "data", "www", "index.html")
    out = os.path.join(root, "src", "config", "StudioPage.h")
    with open(src, "rb") as fh:
        html = fh.read()

    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(html)
    data = buf.getvalue()

    lines = [
        "/**",
        " * @file StudioPage.h",
        " * @brief GENERATED by tools/embed_studio.py from data/www/index.html -",
        " *        do not edit. The Gauge Studio page, gzipped (%d -> %d bytes)."
        % (len(html), len(data)),
        " */",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "static const uint8_t STUDIO_HTML_GZ[] = {",
    ]
    for i in range(0, len(data), 20):
        lines.append("    " + " ".join("0x%02X," % b for b in data[i:i + 20]))
    lines += [
        "};",
        "static const size_t STUDIO_HTML_GZ_LEN = sizeof(STUDIO_HTML_GZ);",
        "",
    ]
    text = "\n".join(lines)

    old = None
    if os.path.exists(out):
        with open(out, "r", encoding="utf-8") as fh:
            old = fh.read()
    if old != text:
        with open(out, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print("embed_studio: %s (%d bytes gzipped)" % (out, len(data)))


build(project_dir())
