/**
 * @file ConfigManager.cpp
 * @ingroup config
 * @brief LittleFS persistence + Gauge Studio captive portal implementation.
 */
#include "ConfigManager.h"

#include "StudioPage.h"     // generated by tools/embed_studio.py

#include <lvgl.h>

#include <LittleFS.h>
#include <WiFi.h>

#include "DisplayManager.h"
#include "UIBuilder.h"
#include "HardwareConfig.h"
#include "MasterPacket.h"
#include "TelemetryStore.h"

ConfigManager Config;

static constexpr const char *LAYOUT_PATH = "/layout.json";
/** Written first, then renamed over LAYOUT_PATH — see persistLayout(). */
static constexpr const char *LAYOUT_TMP  = "/layout.tmp";

/** Filesystem partition label. MUST match the Name column of the filesystem
 *  row in partitions_custom.csv — Arduino's LittleFS locates its partition by
 *  label, not by subtype, and silently fails to mount when they disagree. */
static constexpr const char *FS_PARTITION_LABEL = "spiffs";

/* Minimal built-in layout used only when LittleFS holds no layout.json
 * (e.g. first flash without `pio run -t uploadfs`). The full annotated
 * example lives in data/layout.json. */
static const char DEFAULT_LAYOUT[] PROGMEM = R"JSON({
  "version": 2,
  "global": { "smoothing_alpha": 0.35, "lerp_speed": 0.18,
              "stale_timeout_ms": 1500, "swipe_anim_ms": 250,
              "day_bg": "#101418", "night_bg": "#000000" },
  "warnings": { "enabled": true, "strip": true, "strip_position": "bottom",
                "strip_mode": "always", "peek_secs": 6, "popups": true,
                "lamps": {} },
  "screens": [
    { "id": "dash", "type": "dash", "label": "DASH" },
    { "id": "tach", "type": "meter_gauge", "metric_id": "0x010C",
      "label": "RPM", "units": "x1000", "decimals": 0,
      "min": 0, "max": 8000, "major_tick_every": 1000,
      "arc": { "start_angle": 135, "end_angle": 45, "width": 14,
               "color": "#00E5FF", "bg_color": "#1A2A33" },
      "thresholds": {
        "warning":  { "value": 6200, "hysteresis": 200, "color": "#FFC400" },
        "critical": { "value": 7000, "hysteresis": 150, "color": "#FF1744",
                      "overlay_text": "SHIFT!" } } },
    { "id": "diag", "type": "diag" }
  ]
})JSON";

/*
 * The dash screen added to an older layout by migrateLayout(). Every part is
 * spelled out, so the studio shows what can be changed.
 */
static const char DASH_SCREEN[] PROGMEM = R"JSON({
  "id": "dash", "type": "dash", "label": "DASH",
  "tach":  { "metric_id": "0x010C", "label": "RPM", "max": 8000, "redline": 6500 },
  "speed": { "metric_id": "0x010D", "units": "km/h", "max": 260 },
  "gear":  { "metric_id": "0x1005" },
  "fuel":  { "metric_id": "0x012F", "units": "%",
             "thresholds": { "warning": { "value": 12, "hysteresis": 3,
                                          "direction": "below" } } },
  "temp":  { "metric_id": "0x0105", "min": 40, "max": 130,
             "thresholds": { "warning":  { "value": 105, "hysteresis": 3 },
                             "critical": { "value": 110, "hysteresis": 3 } } },
  "info": [
    { "metric_id": "0x0142", "label": "BATT",  "units": "V",   "decimals": 1 },
    { "metric_id": "0x015C", "label": "OIL",   "units": "\u00B0C" },
    { "metric_id": "0x010F", "label": "IAT",   "units": "\u00B0C" },
    { "metric_id": "0x1001", "label": "BOOST", "units": "bar", "decimals": 2 }
  ],
  "shift_light": { "rpm": 6500, "start": 5000 },
  "lamps": true, "ghost_lamps": true
})JSON";

static const char WARNINGS_DEFAULT[] PROGMEM = R"JSON({
  "enabled": true, "strip": true, "strip_position": "bottom",
  "strip_mode": "always", "peek_secs": 6, "popups": true,
  "lamps": {}
})JSON";

/* ────────────────────────────── lifecycle ───────────────────────────────── */

void ConfigManager::begin() {
    // Two-stage mount. Formatting is the fallback, never the first move: a
    // partition that fails to mount once must not silently erase an uploaded
    // `uploadfs` image. Only a genuinely blank partition gets formatted.
    if (!LittleFS.begin(false, "/littlefs", 10, FS_PARTITION_LABEL)) {
        log_w("LittleFS mount failed — formatting (expected on first flash)");
        if (!LittleFS.begin(true, "/littlefs", 10, FS_PARTITION_LABEL)) {
            log_e("LittleFS unavailable: no data partition labelled '%s'",
                  FS_PARTITION_LABEL);
            return;
        }
    }
    log_i("LittleFS mounted: %u/%u KB used, Gauge Studio built in (%u B)",
          (unsigned)(LittleFS.usedBytes() / 1024), (unsigned)(LittleFS.totalBytes() / 1024),
          (unsigned)STUDIO_HTML_GZ_LEN);

    if (!LittleFS.exists("/assets")) LittleFS.mkdir("/assets");

    if (!loadLayout()) {
        log_w("layout.json missing/corrupt — writing built-in default");
        writeDefaultLayout();
        loadLayout();
    }
    if (migrateLayout()) {
        log_i("layout: updated to version 2 (warning lamps, dash screen)");
        persistLayout();
    }
}

bool ConfigManager::saveTouchCal(const TouchCal &c) {
    JsonObject o = _layout["global"]["touch_cal"].to<JsonObject>();
    o["hx"]    = c.hx;
    o["hy"]    = c.hy;
    o["vx"]    = c.vx;
    o["vy"]    = c.vy;
    o["hlen"]  = c.hLen;
    o["vlen"]  = c.vLen;
    o["valid"] = c.valid;

    // Written straight to flash rather than waiting for a Save in the portal:
    // calibration is done on the device, often with no portal open at all, and
    // having to repeat it after every power cycle would defeat the point.
    if (!persistLayout()) { log_e("touch calibration: layout write failed"); return false; }
    log_i("touch calibration saved: h=(%.2f,%.2f) v=(%.2f,%.2f) len=%.0f/%.0f",
          c.hx, c.hy, c.vx, c.vy, c.hLen, c.vLen);
    return true;
}

bool ConfigManager::loadLayoutFrom(const char *path) {
    File f = LittleFS.open(path, "r");
    if (!f) return false;
    DeserializationError err = deserializeJson(_layout, f);
    f.close();
    if (err) {
        log_e("%s parse error: %s", path, err.c_str());
        return false;
    }
    return _layout["screens"].is<JsonArray>() &&
           _layout["screens"].as<JsonArray>().size() > 0;
}

bool ConfigManager::loadLayout() {
    if (loadLayoutFrom(LAYOUT_PATH)) return true;
    // A save interrupted between writing the new file and renaming it in
    // leaves a complete layout under the temporary name. Rather that than
    // the built-in default, which would lose the touch calibration too.
    if (LittleFS.exists(LAYOUT_TMP) && loadLayoutFrom(LAYOUT_TMP)) {
        log_w("layout: recovered from an interrupted save");
        persistLayout();
        return true;
    }
    return false;
}

bool ConfigManager::commitLayoutTmp(size_t written, size_t expected) {
    if (!written || written != expected) {
        // A short write (flash full) must never replace a good file.
        log_e("layout: wrote %u of %u bytes - keeping the previous layout",
              (unsigned)written, (unsigned)expected);
        LittleFS.remove(LAYOUT_TMP);
        return false;
    }
    // LittleFS renames over an existing file atomically; removing the old
    // one first would open a window with no layout at all. The remove is only
    // the fallback for a layer that refuses to overwrite.
    if (!LittleFS.rename(LAYOUT_TMP, LAYOUT_PATH)) {
        LittleFS.remove(LAYOUT_PATH);
        if (!LittleFS.rename(LAYOUT_TMP, LAYOUT_PATH)) {
            log_e("layout: rename failed, layout not saved");
            return false;
        }
    }
    return true;
}

bool ConfigManager::persistLayout() {
    File f = LittleFS.open(LAYOUT_TMP, "w");
    if (!f) return false;
    const size_t expected = measureJsonPretty(_layout);
    const size_t written  = serializeJsonPretty(_layout, f);
    f.close();
    return commitLayoutTmp(written, expected);
}

bool ConfigManager::writeLayoutText(const String &body) {
    File f = LittleFS.open(LAYOUT_TMP, "w");
    if (!f) return false;
    const size_t written = f.print(body);
    f.close();
    return commitLayoutTmp(written, body.length());
}

bool ConfigManager::migrateLayout() {
    if ((_layout["version"] | 1) >= 2) return false;

    bool hasDash = false;
    for (JsonObject s : _layout["screens"].as<JsonArray>())
        hasDash |= !strcmp(s["type"] | "", "dash");
    if (!hasDash) {
        // First in the list, so it is what the display boots into. There is
        // no insert-at-front, so the list is rebuilt around it.
        JsonDocument dash, old;
        deserializeJson(dash, DASH_SCREEN);
        old.set(_layout["screens"]);
        JsonArray screens = _layout["screens"].to<JsonArray>();
        screens.add(dash.as<JsonObjectConst>());
        for (JsonVariantConst v : old.as<JsonArrayConst>()) screens.add(v);
    }
    if (_layout["warnings"].isNull()) {
        JsonDocument w;
        deserializeJson(w, WARNINGS_DEFAULT);
        _layout["warnings"] = w.as<JsonObjectConst>();
    }
    _layout["version"] = 2;
    return true;
}

void ConfigManager::writeDefaultLayout() {
    File f = LittleFS.open(LAYOUT_PATH, "w");
    if (!f) return;
    f.print(FPSTR(DEFAULT_LAYOUT));
    f.close();
}

/* ───────────────────────────── config mode ──────────────────────────────── */

void ConfigManager::enterConfigMode() {
    if (_configMode) return;

    const char *ssid = apSsid();
    const char *pass = apPassword();

    WiFi.mode(WIFI_AP);
    // WPA2 has an 8-character minimum; anything shorter must be an open
    // network rather than silently failing to start the AP.
    if (strlen(pass) >= 8) WiFi.softAP(ssid, pass, wifiChannel());
    else                   WiFi.softAP(ssid, nullptr, wifiChannel());

    _apIP = WiFi.softAPIP().toString();
    _dns.start(53, "*", WiFi.softAPIP());   // captive portal: answer everything
    setupRoutes();
    _server.begin();
    _configMode = true;
    log_i("Config AP '%s' (%s) up at %s", ssid,
          strlen(pass) >= 8 ? "protected" : "open", _apIP.c_str());
}

void ConfigManager::loop() {
    if (!_configMode) return;
    _dns.processNextRequest();
    _server.handleClient();
}

/* ─────────────────────────────── REST API ───────────────────────────────── */

void ConfigManager::sendJsonOk() {
    _server.send(200, "application/json", "{\"ok\":true}");
}

/**
 * @brief Guess a Content-Type from a file extension.
 * @param path Request path or filename.
 * @return A MIME type; "application/octet-stream" when unrecognized.
 */
static const char *mimeFor(const String &path) {
    if (path.endsWith(".html")) return "text/html";
    if (path.endsWith(".css"))  return "text/css";
    if (path.endsWith(".js"))   return "application/javascript";
    if (path.endsWith(".json")) return "application/json";
    if (path.endsWith(".png"))  return "image/png";
    if (path.endsWith(".svg"))  return "image/svg+xml";
    return "application/octet-stream";
}

void ConfigManager::setupRoutes() {
    // ---- Gauge Studio SPA -------------------------------------------------
    _server.on("/", HTTP_GET, [this]() {
        // Compiled in, gzipped: every browser accepts gzip, and it is a
        // quarter of the size to hold in flash and to send over the AP.
        _server.sendHeader("Content-Encoding", "gzip");
        _server.sendHeader("Cache-Control", "no-cache");
        _server.send_P(200, "text/html",
                       reinterpret_cast<const char *>(STUDIO_HTML_GZ),
                       STUDIO_HTML_GZ_LEN);
    });

    // ---- layout -----------------------------------------------------------
    _server.on("/api/layout", HTTP_GET, [this]() {
        File f = LittleFS.open(LAYOUT_PATH, "r");
        if (!f) { _server.send(404, "application/json", "{\"error\":\"none\"}"); return; }
        _server.streamFile(f, "application/json");
        f.close();
    });

    _server.on("/api/layout", HTTP_POST, [this]() {
        const String &body = _server.arg("plain");
        JsonDocument probe;                       // validate before persisting
        DeserializationError err = deserializeJson(probe, body);
        if (err || !probe["screens"].is<JsonArray>()) {
            _server.send(400, "application/json",
                         String("{\"error\":\"invalid layout: ") +
                         (err ? err.c_str() : "screens[] missing") + "\"}");
            return;
        }
        if (!writeLayoutText(body)) {
            _server.send(500, "application/json", "{\"error\":\"fs write\"}");
            return;
        }
        _layout = probe;                          // hot-swap in RAM; UI rebuild
        sendJsonOk();                             // happens on reboot
    });

    // ---- live telemetry (for the studio's live preview) -------------------
    _server.on("/api/live", HTTP_GET, [this]() {
        // Static: 256 views would not fit on the web handler's stack.
        static MetricView views[TelemetryStore::MAX_SLOTS];
        size_t n = Telemetry.snapshot(views, TelemetryStore::MAX_SLOTS);
        LinkStats st = Telemetry.stats();

        JsonDocument doc;
        doc["link_up"] = Telemetry.linkUp();
        doc["pps"]     = st.packetsPerSecond;
        doc["drops"]   = st.packetsDropped;
        JsonArray arr  = doc["metrics"].to<JsonArray>();
        for (size_t i = 0; i < n; i++) {
            JsonObject m = arr.add<JsonObject>();
            char idbuf[8];
            snprintf(idbuf, sizeof(idbuf), "0x%04X", views[i].id);
            m["id"]     = idbuf;
            m["value"]  = views[i].raw;
            m["peak"]   = views[i].peak;
            m["flags"]  = views[i].flags;
            m["age_ms"] = views[i].ageMs;
        }
        String out;
        serializeJson(doc, out);
        _server.send(200, "application/json", out);
    });

    // ---- system info ------------------------------------------------------
    _server.on("/api/info", HTTP_GET, [this]() {
        JsonDocument doc;
        doc["firmware"]   = FIRMWARE_VERSION;
        doc["proto"]      = TELEMETRY_PROTO_VERSION;
        doc["channel"]    = wifiChannel();
        // The MAC actually heard — this is the value to paste into the peer
        // filter, so surfacing it saves the user hunting for it on the master.
        doc["peer_mac"]   = Telemetry.peerMac();
        doc["own_mac"]    = WiFi.macAddress();
        doc["heap_free"]  = ESP.getFreeHeap();
        doc["fs_total"]   = LittleFS.totalBytes();
        doc["fs_used"]    = LittleFS.usedBytes();
        doc["uptime_s"]   = millis() / 1000;
        // The LVGL heap is a fixed pool (lv_conf.h LV_MEM_SIZE), separate
        // from the one above; the screens and lamps all live in it.
        lv_mem_monitor_t mon;
        lv_mem_monitor(&mon);
        doc["lvgl_used"]  = mon.total_size - mon.free_size;
        doc["lvgl_total"] = mon.total_size;
        String out;
        serializeJson(doc, out);
        _server.send(200, "application/json", out);
    });

    // ---- asset management -------------------------------------------------
    _server.on("/api/assets", HTTP_GET, [this]() {
        JsonDocument doc;
        JsonArray arr = doc["assets"].to<JsonArray>();
        File dir = LittleFS.open("/assets");
        if (dir && dir.isDirectory()) {
            File f = dir.openNextFile();
            while (f) {
                JsonObject o = arr.add<JsonObject>();
                o["name"] = String(f.name());
                o["size"] = f.size();
                f = dir.openNextFile();
            }
        }
        String out;
        serializeJson(doc, out);
        _server.send(200, "application/json", out);
    });

    _server.on("/api/asset", HTTP_POST,
               [this]() { sendJsonOk(); },
               [this]() { handleAssetUpload(); });

    _server.on("/api/asset/delete", HTTP_POST, [this]() {
        String name = _server.arg("name");
        name.replace("..", "");                    // no path traversal
        name.replace("/", "");
        if (name.length() && LittleFS.remove("/assets/" + name)) sendJsonOk();
        else _server.send(404, "application/json", "{\"error\":\"not found\"}");
    });

    /*
     * Live colour calibration.
     *
     * Applied to the panel immediately and stored in the in-memory layout, but
     * NOT written to flash - so sliders can be dragged freely while watching
     * the screen, and only an explicit Save makes it permanent. That also
     * means a bad setting is undone by a power cycle.
     */
    _server.on("/api/calib", HTTP_POST, [this]() {
        JsonDocument body;
        if (deserializeJson(body, _server.arg("plain"))) {
            _server.send(400, "application/json", "{\"error\":\"bad json\"}");
            return;
        }
        const float r = body["r"] | 1.0f;
        const float g = body["g"] | 1.0f;
        const float b = body["b"] | 1.0f;
        _layout["global"]["color_gain_r"] = r;
        _layout["global"]["color_gain_g"] = g;
        _layout["global"]["color_gain_b"] = b;
        Display.setCalibration(r, g, b);
        // Get the AP screen out of the way so the change is actually visible.
        UI.showColorPreview();
        sendJsonOk();
    });

    /* Start the on-device touch wizard from the portal, for when swipes are
     * broken badly enough that reaching a menu by swiping is not an option. */
    _server.on("/api/touchcal", HTTP_POST, [this]() {
        UI.startTouchCalibration();
        sendJsonOk();
    });

    // ---- actions ----------------------------------------------------------
    _server.on("/api/peaks/reset", HTTP_POST, [this]() {
        Telemetry.resetPeaks();
        sendJsonOk();
    });

    _server.on("/api/reboot", HTTP_POST, [this]() {
        sendJsonOk();
        delay(300);
        ESP.restart();
    });

    // ---- static files + captive-portal fallback ---------------------------
    _server.onNotFound([this]() {
        String path = _server.uri();
        if (LittleFS.exists(path)) {
            File f = LittleFS.open(path, "r");
            _server.streamFile(f, mimeFor(path));
            f.close();
            return;
        }
        // Captive-portal probes (generate_204, hotspot-detect, ncsi…) and any
        // unknown URL are redirected to the studio.
        _server.sendHeader("Location", "http://" + _apIP + "/", true);
        _server.send(302, "text/plain", "");
    });
}

void ConfigManager::handleAssetUpload() {
    HTTPUpload &up = _server.upload();
    if (up.status == UPLOAD_FILE_START) {
        String name = up.filename;
        int slash = name.lastIndexOf('/');         // basename only
        if (slash >= 0) name = name.substring(slash + 1);
        name.replace("..", "");
        _uploadFile = LittleFS.open("/assets/" + name, "w");
        log_i("Asset upload start: %s", name.c_str());
    } else if (up.status == UPLOAD_FILE_WRITE) {
        if (_uploadFile) _uploadFile.write(up.buf, up.currentSize);
    } else if (up.status == UPLOAD_FILE_END) {
        if (_uploadFile) {
            _uploadFile.close();
            log_i("Asset upload done: %u bytes", (unsigned)up.totalSize);
        }
    } else if (up.status == UPLOAD_FILE_ABORTED) {
        if (_uploadFile) _uploadFile.close();
    }
}
